insert into hasQ (InID, qname, qlevel) values (8, 'Beginner Training', 2);
insert into hasQ (InID, qname, qlevel) values (9, 'Personal Training', 2);
insert into hasQ (InID, qname, qlevel) values (9, 'Boxing', 2);
insert into hasQ (InID, qname, qlevel) values (10, 'Pilatis', 3);
insert into hasQ (InID, qname, qlevel) values (11, 'Cardio', 1);
insert into hasQ (InID, qname, qlevel) values (3, 'Crossfit', 3);
insert into hasQ (InID, qname, qlevel) values (2, 'First Aid', 1);
insert into hasQ (InID, qname, qlevel) values (17, 'Heavy Weights', 1);
insert into hasQ (InID, qname, qlevel) values (20, 'Nutritionist', 3);
insert into hasQ (InID, qname, qlevel) values (11, 'Personal Training', 2);
insert into hasQ (InID, qname, qlevel) values (10, 'Heavy Weights', 1);
insert into hasQ (InID, qname, qlevel) values (12, 'Fitness Planning', 3);
insert into hasQ (InID, qname, qlevel) values (5, 'Equipment Maintenance', 2);
insert into hasQ (InID, qname, qlevel) values (3, 'Exercise Equipment', 1);
insert into hasQ (InID, qname, qlevel) values (6, 'Yoga Instructor', 1);
insert into hasQ (InID, qname, qlevel) values (2, 'Long distance running', 2);
insert into hasQ (InID, qname, qlevel) values (15, 'Cardio', 2);
insert into hasQ (InID, qname, qlevel) values (12, 'Long distance running', 2);
insert into hasQ (InID, qname, qlevel) values (3, 'Cardio', 1);
insert into hasQ (InID, qname, qlevel) values (19, 'Personal Training', 3);
insert into hasQ (InID, qname, qlevel) values (14, 'Boxing', 2);
insert into hasQ (InID, qname, qlevel) values (1, 'Nutritionist', 3);
insert into hasQ (InID, qname, qlevel) values (20, 'Exercise Equipment', 1);
insert into hasQ (InID, qname, qlevel) values (16, 'Slimming', 2);
insert into hasQ (InID, qname, qlevel) values (11, 'Kineisology Knowledge', 2);
insert into hasQ (InID, qname, qlevel) values (7, 'Personal Training', 2);
insert into hasQ (InID, qname, qlevel) values (11, 'Exercise Equipment', 3);
insert into hasQ (InID, qname, qlevel) values (20, 'Heavy Weights', 1);
insert into hasQ (InID, qname, qlevel) values (11, 'Beginner Training', 1);
insert into hasQ (InID, qname, qlevel) values (1, 'Cardio', 2);
insert into hasQ (InID, qname, qlevel) values (11, 'Crossfit', 3);
insert into hasQ (InID, qname, qlevel) values (20, 'Nutritionist', 2);
insert into hasQ (InID, qname, qlevel) values (5, 'First Aid', 2);
insert into hasQ (InID, qname, qlevel) values (6, 'Crossfit', 1);
insert into hasQ (InID, qname, qlevel) values (17, 'Kineisology Knowledge', 1);
insert into hasQ (InID, qname, qlevel) values (20, 'Pilatis', 2);
insert into hasQ (InID, qname, qlevel) values (13, 'Beginner Training', 1);
insert into hasQ (InID, qname, qlevel) values (13, 'Group Training', 2);
insert into hasQ (InID, qname, qlevel) values (4, 'Cardio', 3);
insert into hasQ (InID, qname, qlevel) values (20, 'Crossfit', 3);
insert into hasQ (InID, qname, qlevel) values (16, 'Kineisology Knowledge', 1);
insert into hasQ (InID, qname, qlevel) values (15, 'Yoga Instructor', 1);
insert into hasQ (InID, qname, qlevel) values (4, 'Swimming', 1);
insert into hasQ (InID, qname, qlevel) values (16, 'Nutritionist', 2);
insert into hasQ (InID, qname, qlevel) values (9, 'Pilatis', 1);
insert into hasQ (InID, qname, qlevel) values (19, 'Fitness Planning', 1);
insert into hasQ (InID, qname, qlevel) values (14, 'Physiology Knowledge', 1);
insert into hasQ (InID, qname, qlevel) values (3, 'Group Training', 2);
insert into hasQ (InID, qname, qlevel) values (11, 'Crossfit', 3);
insert into hasQ (InID, qname, qlevel) values (1, 'Long distance running', 3);
insert into hasQ (InID, qname, qlevel) values (14, 'Group Training', 3);
insert into hasQ (InID, qname, qlevel) values (19, 'Physiology Knowledge', 2);
insert into hasQ (InID, qname, qlevel) values (5, 'Fitness Planning', 1);
insert into hasQ (InID, qname, qlevel) values (8, 'First Aid', 2);
insert into hasQ (InID, qname, qlevel) values (14, 'Fitness Planning', 2);
insert into hasQ (InID, qname, qlevel) values (6, 'Physiology Knowledge', 1);
insert into hasQ (InID, qname, qlevel) values (13, 'Exercise Equipment', 1);
insert into hasQ (InID, qname, qlevel) values (19, 'Slimming', 3);
insert into hasQ (InID, qname, qlevel) values (15, 'Cardio', 1);
insert into hasQ (InID, qname, qlevel) values (12, 'Crossfit', 2);
insert into hasQ (InID, qname, qlevel) values (2, 'Physiology Knowledge', 1);
insert into hasQ (InID, qname, qlevel) values (9, 'Slimming', 3);
insert into hasQ (InID, qname, qlevel) values (15, 'Cardio', 1);
insert into hasQ (InID, qname, qlevel) values (5, 'Heavy Weights', 3);
insert into hasQ (InID, qname, qlevel) values (2, 'Physiology Knowledge', 1);
insert into hasQ (InID, qname, qlevel) values (15, 'Personal Training', 1);
insert into hasQ (InID, qname, qlevel) values (9, 'Beginner Training', 1);
insert into hasQ (InID, qname, qlevel) values (14, 'Cardio', 3);
insert into hasQ (InID, qname, qlevel) values (3, 'Yoga Instructor', 2);
insert into hasQ (InID, qname, qlevel) values (1, 'Beginner Training', 1);
insert into hasQ (InID, qname, qlevel) values (11, 'Tennis', 1);
insert into hasQ (InID, qname, qlevel) values (8, 'Tennis', 2);
insert into hasQ (InID, qname, qlevel) values (17, 'First Aid', 2);
insert into hasQ (InID, qname, qlevel) values (16, 'Cardio', 1);
insert into hasQ (InID, qname, qlevel) values (6, 'Swimming', 1);
insert into hasQ (InID, qname, qlevel) values (9, 'Pilatis', 1);
insert into hasQ (InID, qname, qlevel) values (1, 'Tennis', 3);
insert into hasQ (InID, qname, qlevel) values (18, 'Group Training', 1);
insert into hasQ (InID, qname, qlevel) values (20, 'Beginner Training', 3);
insert into hasQ (InID, qname, qlevel) values (4, 'Exercise Equipment', 2);
insert into hasQ (InID, qname, qlevel) values (1, 'Long distance running', 1);
insert into hasQ (InID, qname, qlevel) values (17, 'Cardio', 1);
insert into hasQ (InID, qname, qlevel) values (12, 'Tennis', 2);
insert into hasQ (InID, qname, qlevel) values (12, 'Exercise Equipment', 3);
insert into hasQ (InID, qname, qlevel) values (14, 'First Aid', 1);
insert into hasQ (InID, qname, qlevel) values (12, 'Exercise Equipment', 2);
insert into hasQ (InID, qname, qlevel) values (20, 'Long distance running', 1);
insert into hasQ (InID, qname, qlevel) values (15, 'Slimming', 2);
insert into hasQ (InID, qname, qlevel) values (12, 'Physiology Knowledge', 2);
insert into hasQ (InID, qname, qlevel) values (3, 'Yoga Instructor', 3);
insert into hasQ (InID, qname, qlevel) values (17, 'Nutritionist', 3);
insert into hasQ (InID, qname, qlevel) values (16, 'Cardio', 2);
insert into hasQ (InID, qname, qlevel) values (10, 'Fitness Planning', 1);
insert into hasQ (InID, qname, qlevel) values (5, 'Long distance running', 1);
insert into hasQ (InID, qname, qlevel) values (7, 'Physiology Knowledge', 3);
insert into hasQ (InID, qname, qlevel) values (9, 'Kineisology Knowledge', 1);
insert into hasQ (InID, qname, qlevel) values (3, 'Pilatis', 3);
insert into hasQ (InID, qname, qlevel) values (17, 'Yoga Instructor', 1);
insert into hasQ (InID, qname, qlevel) values (3, 'Slimming', 1);
insert into hasQ (InID, qname, qlevel) values (5, 'Personal Training', 3);
