insert into Qualifications (qname) values ('Fitness Planning');
insert into Qualifications (qname) values ('Physiology Knowledge');
insert into Qualifications (qname) values ('Exercise Equipment');
insert into Qualifications (qname) values ('Nutritionist');
insert into Qualifications (qname) values ('First Aid');
insert into Qualifications (qname) values ('Swimming');
insert into Qualifications (qname) values ('Kineisology Knowledge');
insert into Qualifications (qname) values ('Long distance running');
insert into Qualifications (qname) values ('Tennis');
insert into Qualifications (qname) values ('Pilatis');
insert into Qualifications (qname) values ('Yoga Instructor');
insert into Qualifications (qname) values ('Equipment Maintenance');
insert into Qualifications (qname) values ('Slimming');
insert into Qualifications (qname) values ('Heavy Weights');
insert into Qualifications (qname) values ('Cardio');
insert into Qualifications (qname) values ('Beginner Training');
insert into Qualifications (qname) values ('Boxing');
insert into Qualifications (qname) values ('Crossfit');
insert into Qualifications (qname) values ('Personal Training');
insert into Qualifications (qname) values ('Group Training');
